# Generated by Django 5.1.4 on 2024-12-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_owner_room_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="users",
            new_name="players",
        ),
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.CharField(default="Человек паук", max_length=255),
        ),
    ]
