# Generated by Django 5.1.4 on 2024-12-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_rename_users_room_players_alter_room_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.CharField(default="Человек Паук", max_length=255),
        ),
    ]
