# Generated by Django 5.1.4 on 2025-01-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_alter_room_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
