# Generated by Django 5.1.4 on 2025-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_room_is_active_alter_room_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="token",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
