# Generated by Django 5.1.4 on 2025-01-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_room_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="max_players",
            field=models.PositiveIntegerField(default=14),
        ),
    ]
