# Generated by Django 5.1.4 on 2025-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0008_room_max_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="link_token",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
