# Generated by Django 5.1.4 on 2025-01-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0009_room_link_token_alter_room_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="players_score",
            field=models.JSONField(default=list),
        ),
    ]
