# Generated by Django 5.1.4 on 2025-01-17 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0010_room_players_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="players_score",
        ),
    ]
