# Generated by Django 5.1.4 on 2025-01-18 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0011_remove_room_players_score"),
        ("scores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerscore",
            unique_together={("user", "room")},
        ),
    ]
