# Generated by Django 5.1.4 on 2025-01-12 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_last_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_active",
        ),
    ]
