# Generated by Django 5.1.4 on 2025-01-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
