# Generated by Django 5.1.4 on 2025-01-16 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gameScore",
        ),
    ]
